In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy
import csv
import itertools

In [3]:
cookie_all_basic_df = pd.read_pickle("cookie_df.pkl")

In [4]:
cookie_all_basic_df.head()

,drawbridge_handle,cookie_id,computer_os_type,computer_browser_version,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7
0,-1,id_10,computer_os_type_203,computer_browser_version_1158,country_146,1,anonymous_c1_1307,anonymous_c2_18778,15,1,204
1,handle_609762,id_100,computer_os_type_133,computer_browser_version_875,country_146,1,anonymous_c1_753,-1,41,1,204
2,handle_1622320,id_1000,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_906,anonymous_c2_751,40,140,204
3,-1,id_10000,computer_os_type_203,computer_browser_version_36,country_146,1,anonymous_c1_255,anonymous_c2_2725,34,140,204
4,handle_1286628,id_100000,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_255,anonymous_c2_235,52,134,204

In [5]:
cookie_training_set_df = cookie_all_basic_df[cookie_all_basic_df['drawbridge_handle'] != '-1']

In [6]:
cookie_training_set_df.head()

,drawbridge_handle,cookie_id,computer_os_type,computer_browser_version,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7
1,handle_609762,id_100,computer_os_type_133,computer_browser_version_875,country_146,1,anonymous_c1_753,-1,41,1,204
2,handle_1622320,id_1000,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_906,anonymous_c2_751,40,140,204
4,handle_1286628,id_100000,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_255,anonymous_c2_235,52,134,204
6,handle_226230,id_1000006,computer_os_type_203,computer_browser_version_1238,-1,1,-1,-1,1,183,183
8,handle_15216,id_1000008,computer_os_type_200,computer_browser_version_482,country_146,0,anonymous_c1_1179,anonymous_c2_2683,40,74,204

In [7]:
cookie_training_set_df = pd.concat([cookie_training_set_df, pd.get_dummies(cookie_training_set_df['country'])], axis=1)

In [8]:
cookie_training_set_df.head()

,drawbridge_handle,cookie_id,computer_os_type,computer_browser_version,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,...,country_90,country_91,country_92,country_93,country_94,country_95,country_96,country_97,country_98,country_99
1,handle_609762,id_100,computer_os_type_133,computer_browser_version_875,country_146,1,anonymous_c1_753,-1,41,1,...,0,0,0,0,0,0,0,0,0,0
2,handle_1622320,id_1000,computer_os_type_203,computer_browser_version_36,country_146,0,anonymous_c1_906,anonymous_c2_751,40,140,...,0,0,0,0,0,0,0,0,0,0
4,handle_1286628,id_100000,computer_os_type_203,computer_browser_version_875,country_146,0,anonymous_c1_255,anonymous_c2_235,52,134,...,0,0,0,0,0,0,0,0,0,0
6,handle_226230,id_1000006,computer_os_type_203,computer_browser_version_1238,-1,1,-1,-1,1,183,...,0,0,0,0,0,0,0,0,0,0
8,handle_15216,id_1000008,computer_os_type_200,computer_browser_version_482,country_146,0,anonymous_c1_1179,anonymous_c2_2683,40,74,...,0,0,0,0,0,0,0,0,0,0

In [9]:
cookie_training_set_df = cookie_training_set_df.drop('country', 1)

In [17]:
cookie_column_list = list(cookie_training_set_df)

In [18]:
cookie_column_list

['drawbridge_handle',
 'cookie_id',
 'computer_os_type',
 'computer_browser_version',
 'anonymous_c0',
 'anonymous_c1',
 'anonymous_c2',
 'anonymous_5',
 'anonymous_6',
 'anonymous_7',
 '-1',
 'country_1',
 'country_10',
 'country_100',
 'country_101',
 'country_103',
 'country_104',
 'country_105',
 'country_106',
 'country_107',
 'country_108',
 'country_109',
 'country_11',
 'country_110',
 'country_111',
 'country_112',
 'country_113',
 'country_114',
 'country_115',
 'country_116',
 'country_117',
 'country_118',
 'country_119',
 'country_12',
 'country_120',
 'country_121',
 'country_122',
 'country_123',
 'country_124',
 'country_125',
 'country_126',
 'country_127',
 'country_128',
 'country_129',
 'country_13',
 'country_130',
 'country_131',
 'country_132',
 'country_133',
 'country_134',
 'country_135',
 'country_136',
 'country_137',
 'country_138',
 'country_139',
 'country_141',
 'country_142',
 'country_143',
 'country_144',
 'country_145',
 'country_146',
 'country_147',
 'country_148',
 'country_149',
 'country_15',
 'country_150',
 'country_151',
 'country_152',
 'country_154',
 'country_155',
 'country_157',
 'country_158',
 'country_159',
 'country_16',
 'country_160',
 'country_161',
 'country_162',
 'country_163',
 'country_164',
 'country_165',
 'country_166',
 'country_168',
 'country_169',
 'country_17',
 'country_170',
 'country_172',
 'country_173',
 'country_174',
 'country_175',
 'country_176',
 'country_177',
 'country_178',
 'country_179',
 'country_18',
 'country_180',
 'country_181',
 'country_182',
 'country_183',
 'country_184',
 'country_185',
 'country_186',
 'country_187',
 'country_188',
 'country_189',
 'country_19',
 'country_190',
 'country_191',
 'country_192',
 'country_193',
 'country_194',
 'country_195',
 'country_196',
 'country_197',
 'country_198',
 'country_199',
 'country_2',
 'country_20',
 'country_200',
 'country_201',
 'country_202',
 'country_203',
 'country_204',
 'country_205',
 'country_207',
 'country_208',
 'country_209',
 'country_21',
 'country_210',
 'country_211',
 'country_212',
 'country_213',
 'country_214',
 'country_216',
 'country_22',
 'country_23',
 'country_24',
 'country_25',
 'country_26',
 'country_27',
 'country_28',
 'country_29',
 'country_3',
 'country_30',
 'country_31',
 'country_32',
 'country_33',
 'country_34',
 'country_35',
 'country_37',
 'country_38',
 'country_39',
 'country_4',
 'country_40',
 'country_41',
 'country_42',
 'country_43',
 'country_44',
 'country_45',
 'country_46',
 'country_47',
 'country_48',
 'country_49',
 'country_5',
 'country_51',
 'country_52',
 'country_53',
 'country_54',
 'country_56',
 'country_57',
 'country_58',
 'country_59',
 'country_6',
 'country_60',
 'country_62',
 'country_64',
 'country_65',
 'country_66',
 'country_67',
 'country_68',
 'country_69',
 'country_7',
 'country_70',
 'country_71',
 'country_72',
 'country_73',
 'country_74',
 'country_75',
 'country_76',
 'country_79',
 'country_8',
 'country_80',
 'country_81',
 'country_82',
 'country_83',
 'country_84',
 'country_85',
 'country_86',
 'country_87',
 'country_88',
 'country_89',
 'country_9',
 'country_90',
 'country_91',
 'country_92',
 'country_93',
 'country_94',
 'country_95',
 'country_96',
 'country_97',
 'country_98',
 'country_99']

In [14]:
dev_train_df = pd.read_pickle("device_training_df.pkl")

In [15]:
dev_train_df = pd.concat([dev_train_df, pd.get_dummies(dev_train_df['country'])], axis=1)

In [16]:
dev_train_df.head()

,drawbridge_handle,device_id,device_type,device_os,country,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,...,country_87,country_89,country_90,country_92,country_93,country_94,country_95,country_96,country_97,country_98
0,handle_292447,id_1000002,devtype_2,devos_138,country_146,1,anonymous_c1_331,anonymous_c2_23084,34,1,...,0,0,0,0,0,0,0,0,0,0
1,handle_1272807,id_1000061,devtype_2,devos_157,country_146,0,anonymous_c1_1350,anonymous_c2_3147,51,1,...,0,0,0,0,0,0,0,0,0,0
2,handle_1644226,id_1000068,devtype_2,devos_157,country_146,0,anonymous_c1_1166,anonymous_c2_11093,41,1,...,0,0,0,0,0,0,0,0,0,0
3,handle_1634852,id_1000149,devtype_4,devos_133,country_146,1,anonymous_c1_1260,anonymous_c2_2456,10,25,...,0,0,0,0,0,0,0,0,0,0
4,handle_1189159,id_1000202,devtype_4,devos_7,country_146,0,anonymous_c1_917,anonymous_c2_19317,5,1,...,0,0,0,0,0,0,0,0,0,0

In [19]:
device_column_list = list(dev_train_df)

In [20]:
device_column_list

['drawbridge_handle',
 'device_id',
 'device_type',
 'device_os',
 'country',
 'anonymous_c0',
 'anonymous_c1',
 'anonymous_c2',
 'anonymous_5',
 'anonymous_6',
 'anonymous_7',
 '-1',
 'country_1',
 'country_101',
 'country_103',
 'country_104',
 'country_105',
 'country_106',
 'country_107',
 'country_111',
 'country_114',
 'country_115',
 'country_116',
 'country_117',
 'country_118',
 'country_119',
 'country_12',
 'country_120',
 'country_121',
 'country_122',
 'country_123',
 'country_124',
 'country_125',
 'country_126',
 'country_127',
 'country_128',
 'country_129',
 'country_13',
 'country_131',
 'country_132',
 'country_133',
 'country_138',
 'country_139',
 'country_141',
 'country_142',
 'country_143',
 'country_145',
 'country_146',
 'country_147',
 'country_149',
 'country_15',
 'country_150',
 'country_151',
 'country_152',
 'country_157',
 'country_159',
 'country_16',
 'country_160',
 'country_161',
 'country_163',
 'country_165',
 'country_166',
 'country_168',
 'country_169',
 'country_17',
 'country_170',
 'country_172',
 'country_173',
 'country_174',
 'country_175',
 'country_176',
 'country_177',
 'country_179',
 'country_18',
 'country_180',
 'country_182',
 'country_183',
 'country_186',
 'country_188',
 'country_190',
 'country_191',
 'country_193',
 'country_194',
 'country_195',
 'country_196',
 'country_197',
 'country_198',
 'country_20',
 'country_200',
 'country_201',
 'country_202',
 'country_204',
 'country_205',
 'country_207',
 'country_208',
 'country_209',
 'country_21',
 'country_211',
 'country_212',
 'country_213',
 'country_216',
 'country_22',
 'country_23',
 'country_24',
 'country_25',
 'country_26',
 'country_27',
 'country_28',
 'country_29',
 'country_3',
 'country_31',
 'country_33',
 'country_34',
 'country_35',
 'country_37',
 'country_38',
 'country_4',
 'country_40',
 'country_41',
 'country_44',
 'country_48',
 'country_49',
 'country_5',
 'country_51',
 'country_53',
 'country_54',
 'country_57',
 'country_58',
 'country_59',
 'country_60',
 'country_62',
 'country_65',
 'country_67',
 'country_68',
 'country_7',
 'country_71',
 'country_72',
 'country_73',
 'country_74',
 'country_79',
 'country_81',
 'country_82',
 'country_83',
 'country_84',
 'country_85',
 'country_86',
 'country_87',
 'country_89',
 'country_90',
 'country_92',
 'country_93',
 'country_94',
 'country_95',
 'country_96',
 'country_97',
 'country_98']

In [22]:
cookie_training_set_df.set_index('cookie_id')

,drawbridge_handle,computer_os_type,computer_browser_version,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7,-1,...,country_90,country_91,country_92,country_93,country_94,country_95,country_96,country_97,country_98,country_99
cookie_id,,,,,,,,,,,,,,,,,,,,,
id_100,handle_609762,computer_os_type_133,computer_browser_version_875,1,anonymous_c1_753,-1,41,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000,handle_1622320,computer_os_type_203,computer_browser_version_36,0,anonymous_c1_906,anonymous_c2_751,40,140,204,0,...,0,0,0,0,0,0,0,0,0,0
id_100000,handle_1286628,computer_os_type_203,computer_browser_version_875,0,anonymous_c1_255,anonymous_c2_235,52,134,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000006,handle_226230,computer_os_type_203,computer_browser_version_1238,1,-1,-1,1,183,183,1,...,0,0,0,0,0,0,0,0,0,0
id_1000008,handle_15216,computer_os_type_200,computer_browser_version_482,0,anonymous_c1_1179,anonymous_c2_2683,40,74,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000009,handle_1043549,computer_os_type_133,computer_browser_version_1158,0,anonymous_c1_1307,anonymous_c2_6720,11,161,203,0,...,0,0,0,0,0,0,0,0,0,0
id_100001,handle_1303003,computer_os_type_133,computer_browser_version_683,0,anonymous_c1_493,anonymous_c2_27360,9,136,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000015,handle_1929259,computer_os_type_26,computer_browser_version_450,0,anonymous_c1_550,anonymous_c2_1338,46,60,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000017,handle_853638,computer_os_type_133,computer_browser_version_1238,1,anonymous_c1_639,anonymous_c2_27190,15,1,165,0,...,0,0,0,0,0,0,0,0,0,0
id_1000022,handle_1204416,computer_os_type_185,computer_browser_version_897,0,-1,-1,7,144,153,1,...,0,0,0,0,0,0,0,0,0,0
id_1000025,handle_1500607,computer_os_type_203,computer_browser_version_875,0,anonymous_c1_317,anonymous_c2_3469,11,1,200,0,...,0,0,0,0,0,0,0,0,0,0
id_1000026,handle_874748,computer_os_type_203,computer_browser_version_36,0,anonymous_c1_673,anonymous_c2_17315,15,165,190,0,...,0,0,0,0,0,0,0,0,0,0
id_1000033,handle_1257881,computer_os_type_146,computer_browser_version_548,0,anonymous_c1_1128,-1,13,1,204,1,...,0,0,0,0,0,0,0,0,0,0
id_1000034,handle_2002832,-1,computer_browser_version_1123,-1,anonymous_c1_645,anonymous_c2_7206,5,18,199,0,...,0,0,0,0,0,0,0,0,0,0
id_1000036,handle_248735,computer_os_type_133,computer_browser_version_875,0,anonymous_c1_1318,anonymous_c2_22839,28,110,204,0,...,0,0,0,0,0,0,0,0,0,0
id_1000037,handle_2061632,computer_os_type_243,computer_browser_version_1395,0,-1,-1,5,1,194,0,...,0,0,0,0,0,0,0,0,0,0
id_1000038,handle_1851795,computer_os_type_203,computer_browser_version_875,0,anonymous_c1_78,anonymous_c2_24726,25,1,196,0,...,0,0,0,0,0,0,0,0,0,0
id_1000039,handle_1068291,computer_os_type_203,computer_browser_version_875,1,anonymous_c1_844,-1,14,1,200,1,...,0,0,0,0,0,0,0,0,0,0
id_1000042,handle_1913675,computer_os_type_203,computer_browser_version_1158,0,-1,-1,26,172,204,1,...,0,0,0,0,0,0,0,0,0,0
id_1000048,handle_47701,computer_os_type_203,computer_browser_version_875,-1,-1,-1,12,1,197,1,...,0,0,0,0,0,0,0,0,0,0
id_1000050,handle_2059273,computer_os_type_203,computer_browser_version_875,-1,anonymous_c1_211,-1,16,1,196,0,...,0,0,0,0,0,0,0,0,0,0
id_1000051,handle_1724748,computer_os_type_133,computer_browser_version_36,0,anonymous_c1_1286,anonymous_c2_22618,10,153,183,0,...,0,0,0,0,0,0,0,0,0,0
id_1000055,handle_523401,computer_os_type_203,computer_browser_version_683,-1,anonymous_c1_276,anonymous_c2_4752,2,182,183,0,...,0,0,0,0,0,0,0,0,0,0
id_1000056,handle_87379,computer_os_type_151,computer_browser_version_1620,1,anonymous_c1_41,anonymous_c2_8400,9,1,201,0,...,0,0,0,0,0,0,0,0,0,0
id_1000059,handle_1892146,computer_os_type_70,computer_browser_version_1238,0,anonymous_c1_1093,anonymous_c2_5166,1,1,201,0,...,0,0,0,0,0,0,0,0,0,0
id_100006,handle_2039528,computer_os_type_164,computer_browser_version_193,0,anonymous_c1_439,anonymous_c2_23828,8,1,199,0,...,0,0,0,0,0,0,0,0,0,0
id_1000063,handle_434975,computer_os_type_243,computer_browser_version_1395,0,anonymous_c1_23,anonymous_c2_1001,22,1,193,0,...,0,0,0,0,0,0,0,0,0,0
id_1000066,handle_1587677,computer_os_type_133,computer_browser_version_36,0,-1,-1,52,141,204,1,...,0,0,0,0,0,0,0,0,0,0
id_1000070,handle_1851828,computer_os_type_228,computer_browser_version_978,1,anonymous_c1_132,-1,15,1,188,0,...,0,0,0,0,0,0,0,0,0,0
id_1000071,handle_1895001,computer_os_type_203,computer_browser_version_875,1,anonymous_c1_331,-1,26,1,201,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
id_999919,handle_1009704,computer_os_type_133,computer_browser_version_875,1,anonymous_c1_255,anonymous_c2_551,17,1,196,0,...,0,0,0,0,0,0,0,0,0,0
id_999920,handle_980543,computer_os_type_203,computer_browser_version_1238,1,anonymous_c1_331,-1,10,132,158,0,...,0,0,0,0,0,0,0,0,0,0
id_999921,handle_1591600,computer_os_type_39,computer_browser_version_894,0,anonymous_c1_1350,anonymous_c2_11554,10,125,162,0,...,0,0,0,0,0,0,0,0,0,0
id_999924,handle_1670918,computer_os_type_203,computer_browser_version_1158,1,-1,-1,17,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999926,handle_2002614,computer_os_type_164,computer_browser_version_193,1,anonymous_c1_323,anonymous_c2_28092,46,53,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999929,handle_556190,computer_os_type_157,computer_browser_version_1232,1,-1,-1,4,11,174,0,...,0,0,0,0,0,0,0,0,0,0
id_999930,handle_670668,computer_os_type_133,computer_browser_version_36,-1,-1,-1,38,118,187,0,...,0,0,0,0,0,0,0,0,0,0
id_999932,handle_1207717,computer_os_type_203,computer_browser_version_377,0,anonymous_c1_1279,-1,5,1,177,1,...,0,0,0,0,0,0,0,0,0,0
id_999934,handle_458152,computer_os_type_133,computer_browser_version_683,1,-1,-1,16,1,192,0,...,0,0,0,0,0,0,0,0,0,0
id_999939,handle_4947,computer_os_type_203,computer_browser_version_897,0,anonymous_c1_1311,-1,6,140,147,0,...,0,0,0,0,0,0,0,0,0,0
id_999940,handle_1804505,computer_os_type_149,computer_browser_version_897,0,anonymous_c1_1220,anonymous_c2_26085,6,32,168,0,...,0,0,0,0,0,0,0,0,0,0
id_999942,handle_1756728,computer_os_type_200,computer_browser_version_1421,0,anonymous_c1_1089,anonymous_c2_9904,43,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999946,handle_1061028,computer_os_type_133,computer_browser_version_683,1,anonymous_c1_470,anonymous_c2_21871,10,106,195,0,...,0,0,0,0,0,0,0,0,0,0
id_999947,handle_88234,computer_os_type_201,computer_browser_version_875,-1,anonymous_c1_60,anonymous_c2_17415,9,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999948,handle_215883,computer_os_type_203,computer_browser_version_36,0,anonymous_c1_455,anonymous_c2_25087,9,145,196,0,...,0,0,0,0,0,0,0,0,0,0
id_99995,handle_1849065,computer_os_type_164,computer_browser_version_875,0,anonymous_c1_505,anonymous_c2_6354,35,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999950,handle_1450942,computer_os_type_248,computer_browser_version_1158,0,anonymous_c1_255,anonymous_c2_26299,5,194,201,0,...,0,0,0,0,0,0,0,0,0,0
id_999951,handle_767887,computer_os_type_203,computer_browser_version_875,1,anonymous_c1_250,-1,44,99,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999952,handle_1860209,computer_os_type_200,computer_browser_version_645,1,-1,-1,46,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999953,handle_567478,computer_os_type_200,computer_browser_version_482,0,anonymous_c1_1086,anonymous_c2_1334,6,193,202,0,...,0,0,0,0,0,0,0,0,0,0
id_99996,handle_1598204,computer_os_type_203,computer_browser_version_377,0,anonymous_c1_804,anonymous_c2_29202,12,115,178,0,...,0,0,0,0,0,0,0,0,0,0
id_999962,handle_1153459,computer_os_type_203,computer_browser_version_377,1,anonymous_c1_94,anonymous_c2_17262,4,1,203,0,...,0,0,0,0,0,0,0,0,0,0
id_999965,handle_2012104,computer_os_type_39,computer_browser_version_1620,0,anonymous_c1_255,anonymous_c2_29197,13,11,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999969,handle_1655772,computer_os_type_39,computer_browser_version_894,-1,anonymous_c1_648,anonymous_c2_2217,45,1,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999970,handle_995610,computer_os_type_133,computer_browser_version_875,0,anonymous_c1_60,anonymous_c2_26167,30,158,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999973,handle_1159003,computer_os_type_243,computer_browser_version_821,1,anonymous_c1_60,anonymous_c2_5262,27,141,204,0,...,0,0,0,0,0,0,0,0,0,0
id_999977,handle_359440,computer_os_type_203,computer_browser_version_1238,1,anonymous_c1_1344,anonymous_c2_21142,4,124,145,1,...,0,0,0,0,0,0,0,0,0,0
id_999978,handle_915360,computer_os_type_203,computer_browser_version_36,0,anonymous_c1_1179,anonymous_c2_7482,8,185,195,0,...,0,0,0,0,0,0,0,0,0,0
id_999992,handle_596633,-1,computer_browser_version_1280,0,-1,-1,34,60,203,0,...,0,0,0,0,0,0,0,0,0,0
id_999999,handle_38844,computer_os_type_109,computer_browser_version_875,1,anonymous_c1_906,anonymous_c2_4906,9,1,204,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
dev_train_df = dev_train_df.drop('country', 1)

In [25]:
dev_train_df = dev_train_df.drop('device_type', 1)

In [27]:
dev_train_df.head()

,drawbridge_handle,device_id,device_os,anonymous_c0,anonymous_c1,anonymous_c2,anonymous_5,anonymous_6,anonymous_7,-1,...,country_87,country_89,country_90,country_92,country_93,country_94,country_95,country_96,country_97,country_98
0,handle_292447,id_1000002,devos_138,1,anonymous_c1_331,anonymous_c2_23084,34,1,204,0,...,0,0,0,0,0,0,0,0,0,0
1,handle_1272807,id_1000061,devos_157,0,anonymous_c1_1350,anonymous_c2_3147,51,1,203,0,...,0,0,0,0,0,0,0,0,0,0
2,handle_1644226,id_1000068,devos_157,0,anonymous_c1_1166,anonymous_c2_11093,41,1,204,0,...,0,0,0,0,0,0,0,0,0,0
3,handle_1634852,id_1000149,devos_133,1,anonymous_c1_1260,anonymous_c2_2456,10,25,198,0,...,0,0,0,0,0,0,0,0,0,0
4,handle_1189159,id_1000202,devos_7,0,anonymous_c1_917,anonymous_c2_19317,5,1,204,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
dev_train_df = dev_train_df.drop('device_os', 1)

In [29]:
dev_train_df = dev_train_df.set_index('device_id')

In [31]:
dev_train_df = dev_train_df.drop('drawbridge_handle', 1)

In [32]:
dev_train_df = dev_train_df.drop('anonymous_c1', 1)

In [33]:
dev_train_df = dev_train_df.drop('anonymous_c2', 1)

In [35]:
dev_train_df = dev_train_df.drop('-1', 1)

In [36]:
dev_train_df.head()

,anonymous_c0,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,...,country_87,country_89,country_90,country_92,country_93,country_94,country_95,country_96,country_97,country_98
device_id,,,,,,,,,,,,,,,,,,,,,
id_1000002,1,34,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000061,0,51,1,203,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000068,0,41,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000149,1,10,25,198,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000202,0,5,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [37]:
dev_train_df = pd.concat([dev_train_df, pd.get_dummies(dev_train_df['anonymous_c0'])], axis=1)

In [38]:
dev_train_df.head()

,anonymous_c0,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,...,country_92,country_93,country_94,country_95,country_96,country_97,country_98,-1,0,1
device_id,,,,,,,,,,,,,,,,,,,,,
id_1000002,1,34,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000061,0,51,1,203,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_1000068,0,41,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_1000149,1,10,25,198,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000202,0,5,1,204,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [40]:
dev_train_df = dev_train_df.drop(-1, 1)

In [42]:
dev_train_df = dev_train_df.drop(0, 1)

In [43]:
dev_train_df = dev_train_df.drop(1, 1)

In [44]:
dev_train_df = pd.concat([dev_train_df, pd.get_dummies(dev_train_df['anonymous_c0'], prefix="anonymous_c0")], axis=1)

In [46]:
dev_train_df = dev_train_df.drop('anonymous_c0', 1)

In [47]:
dev_train_df.head()

,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,country_107,...,country_92,country_93,country_94,country_95,country_96,country_97,country_98,anonymous_c0_-1,anonymous_c0_0,anonymous_c0_1
device_id,,,,,,,,,,,,,,,,,,,,,
id_1000002,34,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000061,51,1,203,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_1000068,41,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_1000149,10,25,198,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000202,5,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [49]:
cookie_train_df = cookie_training_set_df.set_index('cookie_id')

In [51]:
cookie_train_df = cookie_train_df.drop('-1', 1)

In [53]:
cookie_train_df = pd.concat([cookie_train_df, pd.get_dummies(cookie_train_df['anonymous_c0'], prefix="anonymous_c0")], axis=1)

In [55]:
cookie_train_df = cookie_train_df.drop('drawbridge_handle', 1)
cookie_train_df = cookie_train_df.drop('computer_os_type', 1)
cookie_train_df = cookie_train_df.drop('computer_browser_version', 1)
cookie_train_df = cookie_train_df.drop('anonymous_c0', 1)
cookie_train_df = cookie_train_df.drop('anonymous_c1', 1)
cookie_train_df = cookie_train_df.drop('anonymous_c2', 1)

In [56]:
cookie_train_df.head()

,anonymous_5,anonymous_6,anonymous_7,country_1,country_10,country_100,country_101,country_103,country_104,country_105,...,country_93,country_94,country_95,country_96,country_97,country_98,country_99,anonymous_c0_-1,anonymous_c0_0,anonymous_c0_1
cookie_id,,,,,,,,,,,,,,,,,,,,,
id_100,41,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000,40,140,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_100000,52,134,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
id_1000006,1,183,183,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
id_1000008,40,74,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [57]:
device_column_list = list(dev_train_df)

In [58]:
cookie_column_list = list(cookie_train_df)

In [59]:
device_column_list

['anonymous_5',
 'anonymous_6',
 'anonymous_7',
 'country_1',
 'country_101',
 'country_103',
 'country_104',
 'country_105',
 'country_106',
 'country_107',
 'country_111',
 'country_114',
 'country_115',
 'country_116',
 'country_117',
 'country_118',
 'country_119',
 'country_12',
 'country_120',
 'country_121',
 'country_122',
 'country_123',
 'country_124',
 'country_125',
 'country_126',
 'country_127',
 'country_128',
 'country_129',
 'country_13',
 'country_131',
 'country_132',
 'country_133',
 'country_138',
 'country_139',
 'country_141',
 'country_142',
 'country_143',
 'country_145',
 'country_146',
 'country_147',
 'country_149',
 'country_15',
 'country_150',
 'country_151',
 'country_152',
 'country_157',
 'country_159',
 'country_16',
 'country_160',
 'country_161',
 'country_163',
 'country_165',
 'country_166',
 'country_168',
 'country_169',
 'country_17',
 'country_170',
 'country_172',
 'country_173',
 'country_174',
 'country_175',
 'country_176',
 'country_177',
 'country_179',
 'country_18',
 'country_180',
 'country_182',
 'country_183',
 'country_186',
 'country_188',
 'country_190',
 'country_191',
 'country_193',
 'country_194',
 'country_195',
 'country_196',
 'country_197',
 'country_198',
 'country_20',
 'country_200',
 'country_201',
 'country_202',
 'country_204',
 'country_205',
 'country_207',
 'country_208',
 'country_209',
 'country_21',
 'country_211',
 'country_212',
 'country_213',
 'country_216',
 'country_22',
 'country_23',
 'country_24',
 'country_25',
 'country_26',
 'country_27',
 'country_28',
 'country_29',
 'country_3',
 'country_31',
 'country_33',
 'country_34',
 'country_35',
 'country_37',
 'country_38',
 'country_4',
 'country_40',
 'country_41',
 'country_44',
 'country_48',
 'country_49',
 'country_5',
 'country_51',
 'country_53',
 'country_54',
 'country_57',
 'country_58',
 'country_59',
 'country_60',
 'country_62',
 'country_65',
 'country_67',
 'country_68',
 'country_7',
 'country_71',
 'country_72',
 'country_73',
 'country_74',
 'country_79',
 'country_81',
 'country_82',
 'country_83',
 'country_84',
 'country_85',
 'country_86',
 'country_87',
 'country_89',
 'country_90',
 'country_92',
 'country_93',
 'country_94',
 'country_95',
 'country_96',
 'country_97',
 'country_98',
 'anonymous_c0_-1',
 'anonymous_c0_0',
 'anonymous_c0_1']

In [60]:
cookie_column_list

['anonymous_5',
 'anonymous_6',
 'anonymous_7',
 'country_1',
 'country_10',
 'country_100',
 'country_101',
 'country_103',
 'country_104',
 'country_105',
 'country_106',
 'country_107',
 'country_108',
 'country_109',
 'country_11',
 'country_110',
 'country_111',
 'country_112',
 'country_113',
 'country_114',
 'country_115',
 'country_116',
 'country_117',
 'country_118',
 'country_119',
 'country_12',
 'country_120',
 'country_121',
 'country_122',
 'country_123',
 'country_124',
 'country_125',
 'country_126',
 'country_127',
 'country_128',
 'country_129',
 'country_13',
 'country_130',
 'country_131',
 'country_132',
 'country_133',
 'country_134',
 'country_135',
 'country_136',
 'country_137',
 'country_138',
 'country_139',
 'country_141',
 'country_142',
 'country_143',
 'country_144',
 'country_145',
 'country_146',
 'country_147',
 'country_148',
 'country_149',
 'country_15',
 'country_150',
 'country_151',
 'country_152',
 'country_154',
 'country_155',
 'country_157',
 'country_158',
 'country_159',
 'country_16',
 'country_160',
 'country_161',
 'country_162',
 'country_163',
 'country_164',
 'country_165',
 'country_166',
 'country_168',
 'country_169',
 'country_17',
 'country_170',
 'country_172',
 'country_173',
 'country_174',
 'country_175',
 'country_176',
 'country_177',
 'country_178',
 'country_179',
 'country_18',
 'country_180',
 'country_181',
 'country_182',
 'country_183',
 'country_184',
 'country_185',
 'country_186',
 'country_187',
 'country_188',
 'country_189',
 'country_19',
 'country_190',
 'country_191',
 'country_192',
 'country_193',
 'country_194',
 'country_195',
 'country_196',
 'country_197',
 'country_198',
 'country_199',
 'country_2',
 'country_20',
 'country_200',
 'country_201',
 'country_202',
 'country_203',
 'country_204',
 'country_205',
 'country_207',
 'country_208',
 'country_209',
 'country_21',
 'country_210',
 'country_211',
 'country_212',
 'country_213',
 'country_214',
 'country_216',
 'country_22',
 'country_23',
 'country_24',
 'country_25',
 'country_26',
 'country_27',
 'country_28',
 'country_29',
 'country_3',
 'country_30',
 'country_31',
 'country_32',
 'country_33',
 'country_34',
 'country_35',
 'country_37',
 'country_38',
 'country_39',
 'country_4',
 'country_40',
 'country_41',
 'country_42',
 'country_43',
 'country_44',
 'country_45',
 'country_46',
 'country_47',
 'country_48',
 'country_49',
 'country_5',
 'country_51',
 'country_52',
 'country_53',
 'country_54',
 'country_56',
 'country_57',
 'country_58',
 'country_59',
 'country_6',
 'country_60',
 'country_62',
 'country_64',
 'country_65',
 'country_66',
 'country_67',
 'country_68',
 'country_69',
 'country_7',
 'country_70',
 'country_71',
 'country_72',
 'country_73',
 'country_74',
 'country_75',
 'country_76',
 'country_79',
 'country_8',
 'country_80',
 'country_81',
 'country_82',
 'country_83',
 'country_84',
 'country_85',
 'country_86',
 'country_87',
 'country_88',
 'country_89',
 'country_9',
 'country_90',
 'country_91',
 'country_92',
 'country_93',
 'country_94',
 'country_95',
 'country_96',
 'country_97',
 'country_98',
 'country_99',
 'anonymous_c0_-1',
 'anonymous_c0_0',
 'anonymous_c0_1']

In [61]:
add_col_to_device = [col for col in cookie_column_list if col not in device_column_list]

In [62]:
add_col_to_device

['country_10',
 'country_100',
 'country_108',
 'country_109',
 'country_11',
 'country_110',
 'country_112',
 'country_113',
 'country_130',
 'country_134',
 'country_135',
 'country_136',
 'country_137',
 'country_144',
 'country_148',
 'country_154',
 'country_155',
 'country_158',
 'country_162',
 'country_164',
 'country_178',
 'country_181',
 'country_184',
 'country_185',
 'country_187',
 'country_189',
 'country_19',
 'country_192',
 'country_199',
 'country_2',
 'country_203',
 'country_210',
 'country_214',
 'country_30',
 'country_32',
 'country_39',
 'country_42',
 'country_43',
 'country_45',
 'country_46',
 'country_47',
 'country_52',
 'country_56',
 'country_6',
 'country_64',
 'country_66',
 'country_69',
 'country_70',
 'country_75',
 'country_76',
 'country_8',
 'country_80',
 'country_88',
 'country_9',
 'country_91',
 'country_99']

In [63]:
len(add_col_to_device)

56

In [65]:
dev_train_df.shape

(142770, 150)

In [69]:
index_1 = range(142770)
df_to_add = pd.DataFrame(index=index_1, columns=add_col_to_device)
df_to_add = df_to_add.fillna(0)

In [71]:
df_to_add.head()

,country_10,country_100,country_108,country_109,country_11,country_110,country_112,country_113,country_130,country_134,...,country_69,country_70,country_75,country_76,country_8,country_80,country_88,country_9,country_91,country_99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
dev_train = pd.concat([dev_train_df, df_to_add], axis=1)

In [99]:
dev_train.head()

,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,country_107,...,country_69,country_70,country_75,country_76,country_8,country_80,country_88,country_9,country_91,country_99
id_1000002,34,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000061,51,1,203,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000068,41,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000149,10,25,198,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000202,5,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
dev_train = dev_train.fillna(value = 0)

In [78]:
dev_train.head()

,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,country_107,...,country_69,country_70,country_75,country_76,country_8,country_80,country_88,country_9,country_91,country_99
id_1000002,34,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000061,51,1,203,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000068,41,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000149,10,25,198,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_1000202,5,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
device_column_list_check = list(dev_train)
cookie_column_list_check = list(cookie_train_df)
add_col_to_device_check = [col for col in cookie_column_list_check if col not in device_column_list_check]

In [75]:
add_col_to_device_check

[]

In [79]:
import sklearn

In [80]:
from sklearn.metrics.pairwise import cosine_similarity

In [81]:
cosine_sim = cosine_similarity(dev_train.iloc[0:1], cookie_train_df.iloc[0:])

In [82]:
cosine_sim

array([[ 0.99940285,  0.83176646,  0.84315339, ...,  0.7234581 ,
         0.96133968,  0.99263439]])

In [83]:
cosine_sim[0][0:200]

array([ 0.99940285,  0.83176646,  0.84315339,  0.70150504,  0.94327955,
        0.78207799,  0.82884515,  0.96095726,  0.99716672,  0.72664625,
        0.9938858 ,  0.75634898,  0.99481732,  0.98656464,  0.88389938,
        0.99025291,  0.99921834,  0.99543039,  0.76957866,  0.99452872,
        0.99645047,  0.76603127,  0.70402134,  0.99271281,  0.9871524 ,
        0.99215346,  0.99861666,  0.83055709,  0.99629321,  0.99928592,
        0.89827395,  0.82466865,  0.79086314,  0.91284546,  0.75972183,
        0.70153099,  0.71968118,  0.99203158,  0.76683424,  0.99945248,
        0.99198036,  0.99943147,  0.94678069,  0.81800609,  0.99413229,
        0.95092423,  0.89080541,  0.79025955,  0.82025413,  0.99824543,
        0.92045722,  0.98324058,  0.78686058,  0.85426937,  0.99321318,
        0.99883609,  0.8199068 ,  0.99142656,  0.99994193,  0.90354823,
        0.97021733,  0.79084302,  0.99581242,  0.98878884,  0.96162366,
        0.81155838,  0.99079286,  0.96454716,  0.99639151,  0.81264344,
        0.81060657,  0.9967695 ,  0.9767543 ,  0.99879931,  0.92266055,
        0.77798596,  0.82697529,  0.99901971,  0.83697642,  0.99021691,
        0.93120698,  0.99771287,  0.99429869,  0.83057363,  0.78193863,
        0.78799692,  0.72590062,  0.82142556,  0.71613512,  0.95221247,
        0.99923563,  0.78271823,  0.81891324,  0.99639151,  0.92287912,
        0.99712713,  0.81239929,  0.99994193,  0.99639151,  0.75803308,
        0.99563847,  0.98736299,  0.76632757,  0.99938995,  0.77782091,
        0.70153678,  0.9294532 ,  0.85950058,  0.9135503 ,  0.99587878,
        0.99904667,  0.71863072,  0.96031343,  0.99639151,  0.89949488,
        0.99761712,  0.94571863,  0.93093029,  0.99639151,  0.98730188,
        0.99235938,  0.83235504,  0.99618153,  0.76979029,  0.92768   ,
        0.99861549,  0.99953993,  0.99831753,  0.99608956,  0.70473877,
        0.76710659,  0.80311167,  0.99883609,  0.9967695 ,  0.99966659,
        0.99938995,  0.85350546,  0.96984183,  0.82932056,  0.79702065,
        0.99923985,  0.81874109,  0.71202323,  0.99835069,  0.99640125,
        0.99618857,  0.82634936,  0.99904499,  0.71622048,  0.99574682,
        0.99086492,  0.82349061,  0.92648523,  0.98891788,  0.99799619,
        0.99825097,  0.99427523,  0.77071774,  0.99933727,  0.88534003,
        0.99230913,  0.9887688 ,  0.85097945,  0.96799001,  0.99629121,
        0.99639151,  0.99734197,  0.89424862,  0.76902828,  0.81662505,
        0.97576773,  0.99739531,  0.73950945,  0.90924875,  0.97506499,
        0.98836995,  0.96951661,  0.93438054,  0.7662583 ,  0.70144995,
        0.98118518,  0.99964928,  0.99901971,  0.9967695 ,  0.99629121,
        0.90522755,  0.99904667,  0.99912011,  0.99974304,  0.99639151,
        0.70238145,  0.86080726,  0.99639151,  0.99975845,  0.73370064,
        0.98683479,  0.82929945,  0.99835069,  0.98105948,  0.99486842])

In [87]:
import numpy as np
## Can be of any shape.
indices = np.where(cosine_sim==cosine_sim.max())

In [88]:
indices

(array([0]), array([1030438]))

Our first prediction!  That device in location 1 is matched to cookie in location 1030438.  
We can bring up our data to check if it is a match.

In [89]:
cookie_basic_df = pd.read_pickle("cookie_df.pkl")

In [92]:
cookie_basic_df = cookie_basic_df[cookie_basic_df['drawbridge_handle'] != '-1']

In [93]:
cookie_basic_df.iloc[1030438]

drawbridge_handle                           handle_68163
cookie_id                                     id_3682356
computer_os_type                    computer_os_type_133
computer_browser_version    computer_browser_version_875
country                                      country_131
anonymous_c0                                           1
anonymous_c1                                          -1
anonymous_c2                                          -1
anonymous_5                                           34
anonymous_6                                            1
anonymous_7                                          203
Name: 1363364, dtype: object

In [100]:
dev_train.shape

(285540, 206)

In [101]:
dev_train_fix = dev_train.iloc[:142770]

In [104]:
dev_train_fix.tail()

,anonymous_5,anonymous_6,anonymous_7,country_1,country_101,country_103,country_104,country_105,country_106,country_107,...,country_69,country_70,country_75,country_76,country_8,country_80,country_88,country_9,country_91,country_99
id_999836,43,1,203,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_999852,42,1,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_999871,23,127,191,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_9999,5,136,203,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
id_999933,52,25,204,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
dev_train.iloc[0]

anonymous_5     34
anonymous_6      1
anonymous_7    204
country_1        0
country_101      0
country_103      0
country_104      0
country_105      0
country_106      0
country_107      0
country_111      0
country_114      0
country_115      0
country_116      0
country_117      0
country_118      0
country_119      0
country_12       0
country_120      0
country_121      0
country_122      0
country_123      0
country_124      0
country_125      0
country_126      0
country_127      0
country_128      0
country_129      0
country_13       0
country_131      0
              ...
country_19       0
country_192      0
country_199      0
country_2        0
country_203      0
country_210      0
country_214      0
country_30       0
country_32       0
country_39       0
country_42       0
country_43       0
country_45       0
country_46       0
country_47       0
country_52       0
country_56       0
country_6        0
country_64       0
country_66       0
country_69       0
country_70       0
country_75       0
country_76       0
country_8        0
country_80       0
country_88       0
country_9        0
country_91       0
country_99       0
Name: id_1000002, dtype: float64

#Good first step?  They matched on anonymous5, 6 and 7 but not on country.  Probably should filter by country first?

In [106]:
test_on_country_df = cookie_train_df[cookie_train_df['country_146'] == 1]

In [113]:
cosine_sim = cosine_similarity(dev_train.iloc[0:1], test_on_country_df.iloc[1:])

In [114]:
import numpy as np
## Can be of any shape.
max_value = np.where(cosine_sim==cosine_sim.max())

In [115]:
cosine_sim

array([[ 0.83176646,  0.84315339,  0.94327955, ...,  0.7234581 ,
         0.96133968,  0.99263439]])

In [116]:
max_value

(array([0, 0, 0, ..., 0, 0, 0]),
 array([    529,     632,     710, ..., 1319137, 1320174, 1320628]))

In [117]:
max_value[1]

array([    529,     632,     710, ..., 1319137, 1320174, 1320628])

In [118]:
len(max_value[1])

6690